"""
This type stub file was generated by pyright.
"""

class SpotifyBaseException(Exception):
    ...


class SpotifyException(SpotifyBaseException):
    def __init__(self, http_status, code, msg, reason=..., headers=...) -> None:
        ...
    
    def __str__(self) -> str:
        ...
    


class SpotifyOauthError(SpotifyBaseException):
    """ Error during Auth Code or Implicit Grant flow """
    def __init__(self, message, error=..., error_description=..., *args, **kwargs) -> None:
        ...
    


class SpotifyStateError(SpotifyOauthError):
    """ The state sent and state received were different """
    def __init__(self, local_state=..., remote_state=..., message=..., error=..., error_description=..., *args, **kwargs) -> None:
        ...
    


